# Generated by Django 5.1.5 on 2025-07-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizadores',
            name='taxa_respondida',
            field=models.BooleanField(default=False),
        ),
    ]
