# Generated by Django 5.1.5 on 2026-01-07 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_avaliacaomensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app.treino'),
        ),
    ]
