# Generated by Django 5.1.5 on 2025-07-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ausencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ausencias',
            name='taxa_respondida',
        ),
        migrations.AddField(
            model_name='ausencias',
            name='resposta',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=10, null=True),
        ),
    ]
