# Generated by Django 5.1.5 on 2025-07-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_ausencias_taxa_respondida_ausencias_resposta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ausencias',
            old_name='resposta',
            new_name='taxa_respondida',
        ),
    ]
