# Generated by Django 5.1.5 on 2026-01-07 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_reservas_treino'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoTrimestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nivel_satisfacao', models.IntegerField()),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('utilizador', 'ano', 'mes')},
            },
        ),
    ]
