# Generated by Django 5.1.5 on 2026-01-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_avaliacaotrimestral_nivel_satisfacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaotrimestral',
            name='nivel_satisfacao',
            field=models.IntegerField(default=None),
        ),
    ]
