# Generated by Django 5.1.5 on 2025-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_utilizadores_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizadores',
            name='regime',
            field=models.CharField(blank=True, choices=[('regime_livre', 'Regime Livre - 35€'), ('regime_livre+plano_alimentar', 'Regime Livre + Plano Alimentar – 40€ (fidelização de 3 meses)'), ('regime_basico', 'Regime Básico - 32,5€ (2 sessões semanais)'), ('regime_basico+plano_alimentar', 'Regime Básico + Plano Alimentar – 37,5€ - (fidelização de 3 meses)'), ('so_treinos_online', 'Só Treinos Online – 10€')], max_length=30, null=True),
        ),
    ]
