# Generated by Django 5.1.5 on 2026-02-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_avaliacaotrimestral_nivel_satisfacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaomensal',
            name='mes_ausente',
            field=models.BooleanField(default=False),
        ),
    ]
