# Generated by Django 5.1.5 on 2026-02-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_avaliacaomensal_mes_ausente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaomensal',
            name='nivel_satisfacao',
            field=models.IntegerField(null=True),
        ),
    ]
