# Generated by Django 5.1.5 on 2025-09-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_utilizadores_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinosonline',
            name='tipo_treino',
            field=models.CharField(choices=[('mobilidade', 'Mobilidade'), ('força', 'Força'), ('funcional', 'Funcional'), ('metabólico', 'Metabólico'), ('aeróbica', 'Aeróbica')], max_length=20),
        ),
    ]
