# Generated by Django 5.1.5 on 2025-11-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_utilizadores_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nometipotreino',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilizadores',
            name='regime',
            field=models.CharField(blank=True, choices=[('regime_livre', 'Regime Livre - 35€'), ('regime_livre+plano_alimentar', 'Regime Livre + Plano Alimentar – 40€ (fidelização de 3 meses)'), ('regime_basico', 'Regime Básico - 30€ (2 sessões semanais)'), ('regime_basico+plano_alimentar', 'Regime Básico + Plano Alimentar – 37,5€ - (fidelização de 3 meses)'), ('so_treinos_online', 'Só Treinos Online – 10€'), ('regime_kids', 'Regime Kids - 20€'), ('pack_6_aulas', 'Pack 6 Aulas – 25€ (sem desconto familiar)'), ('pack_4_aulas', 'Pack 4 Aulas - 20€ (sem desconto familiar)')], max_length=30, null=True),
        ),
    ]
