# Generated by Django 5.1.5 on 2025-11-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_nometipotreino_id_alter_utilizadores_regime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nometipotreino',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='reservas',
            unique_together={('utilizador', 'treino')},
        ),
    ]
